-- =============================================
-- SETUP
-- =============================================
USE DATABASE SMART_RETAIL_INDIA;

CREATE SCHEMA IF NOT EXISTS RAW_LAYER;
USE SCHEMA RAW_LAYER;

-- =============================================
-- STORAGE INTEGRATION
-- =============================================
CREATE OR REPLACE STORAGE INTEGRATION s3_int
    TYPE                      = EXTERNAL_STAGE
    STORAGE_PROVIDER          = S3
    ENABLED                   = TRUE
    STORAGE_AWS_ROLE_ARN      = 'arn:aws:iam::359166600746:role/snowflake-s3-role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://parthi-snowpipe-sales/'); 

DESC INTEGRATION s3_int;

-- =============================================
-- FILE FORMATS
-- =============================================
CREATE OR REPLACE FILE FORMAT SMART_RETAIL_INDIA.RAW_LAYER.csv_ff
    TYPE                            = 'CSV'
    FIELD_DELIMITER                 = ','
    RECORD_DELIMITER                = '\n'
    SKIP_HEADER                     = 1
    FIELD_OPTIONALLY_ENCLOSED_BY    = '"'
    NULL_IF                         = ('NULL','null','N/A','')
    EMPTY_FIELD_AS_NULL             = TRUE
    TRIM_SPACE                      = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH  = FALSE
    DATE_FORMAT                     = 'YYYY-MM-DD';

CREATE OR REPLACE FILE FORMAT SMART_RETAIL_INDIA.RAW_LAYER.json_ff
    TYPE             = 'JSON'
    STRIP_OUTER_ARRAY = TRUE
    NULL_IF           = ('NULL','null','')
    TRIM_SPACE        = TRUE;

-- =============================================
-- STAGE
-- =============================================
CREATE OR REPLACE STAGE SMART_RETAIL_INDIA.RAW_LAYER.s3_stg
    URL               = 's3://parthi-snowpipe-sales/'
    STORAGE_INTEGRATION = s3_int
    FILE_FORMAT       = (FORMAT_NAME = 'SMART_RETAIL_INDIA.RAW_LAYER.csv_ff');

DESC INTEGRATION S3_INT;

SHOW INTEGRATIONS;

DESC STAGE SMART_RETAIL_INDIA.RAW_LAYER.s3_stg;

-- Refresh 
ALTER STAGE SMART_RETAIL_INDIA.RAW_LAYER.s3_stg REFRESH;

-- Step 2: Integration status check
DESC INTEGRATION S3_INT;

SHOW STAGES;

-- Step 3: Stage list test

-- verify stage can reach S3
LIST @SMART_RETAIL_INDIA.RAW_LAYER.s3_stg;

SHOW PIPES;
ALTER PIPE parthi-snowpipe-sales REFRESH;

-- =============================================
-- CSV RAW TABLES (all VARCHAR)
-- =============================================
CREATE OR REPLACE TABLE SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES (
    SALES_ID        VARCHAR,
    DATE_ID         VARCHAR,
    PRODUCT_ID      VARCHAR,
    CUSTOMER_ID     VARCHAR,
    SALESPERSON_ID  VARCHAR,
    BRANCH_ID       VARCHAR,
    REGION_ID       VARCHAR,
    PROMOTION_ID    VARCHAR,
    PAYMENT_ID      VARCHAR,
    QUANTITY        VARCHAR,
    UNIT_PRICE      VARCHAR,
    SALES_AMOUNT    VARCHAR,
    COST            VARCHAR,
    PROFIT          VARCHAR
);

CREATE OR REPLACE TABLE SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES_TARGET (
    TARGET_ID           VARCHAR,
    DATE_ID             VARCHAR,
    BRANCH_ID           VARCHAR,
    REGION_ID           VARCHAR,
    SALESPERSON_ID      VARCHAR,
    CUSTOMER_SEGMENT_ID VARCHAR,
    TARGET_AMOUNT       VARCHAR
);

CREATE OR REPLACE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_INVENTORY (
    INVENTORY_ID    VARCHAR,
    DATE_ID         VARCHAR,
    PRODUCT_ID      VARCHAR,
    BRANCH_ID       VARCHAR,
    STOCK_IN        VARCHAR,
    STOCK_OUT       VARCHAR,
    AVAILABLE_STOCK VARCHAR,
    REORDER_LEVEL   VARCHAR,
    SAFETY_STOCK    VARCHAR,
    STOCK_STATUS    VARCHAR
);

CREATE OR REPLACE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER_FEEDBACK (
    FEEDBACK_ID       VARCHAR,
    CUSTOMER_ID       VARCHAR,
    PRODUCT_ID        VARCHAR,
    BRANCH_ID         VARCHAR,
    DATE_ID           VARCHAR,
    FEEDBACK_TYPE     VARCHAR,
    RATING            VARCHAR,
    COMMENT           VARCHAR,
    CHANNEL           VARCHAR,
    SENTIMENT         VARCHAR,
    RESOLUTION_STATUS VARCHAR,
    RESPONSE_TIME     VARCHAR
);

-- =============================================
-- JSON RAW TABLES (VARIANT)
-- =============================================
CREATE OR REPLACE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_PRODUCT (
    RAW_DATA VARIANT
);
CREATE OR REPLACE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_DATE(
    RAW_DATA VARIANT
);

-- =============================================
-- PIPES
-- =============================================
CREATE OR REPLACE PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_FACT_SALES
    AUTO_INGEST = TRUE
AS
COPY INTO SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES
FROM @SMART_RETAIL_INDIA.RAW_LAYER.s3_stg/FACT_SALES/
FILE_FORMAT = (FORMAT_NAME = 'SMART_RETAIL_INDIA.RAW_LAYER.csv_ff')
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_FACT_SALES_TARGET
    AUTO_INGEST = TRUE
AS
COPY INTO SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES_TARGET
FROM @SMART_RETAIL_INDIA.RAW_LAYER.s3_stg/FACT_SALES_TARGET/
FILE_FORMAT = (FORMAT_NAME = 'SMART_RETAIL_INDIA.RAW_LAYER.csv_ff')
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_INVENTORY
    AUTO_INGEST = TRUE
AS
COPY INTO SMART_RETAIL_INDIA.RAW_LAYER.DIM_INVENTORY
FROM @SMART_RETAIL_INDIA.RAW_LAYER.s3_stg/DIM_INVENTORY/
FILE_FORMAT = (FORMAT_NAME = 'SMART_RETAIL_INDIA.RAW_LAYER.csv_ff')
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_CUSTOMER_FEEDBACK
    AUTO_INGEST = TRUE
AS
COPY INTO SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER_FEEDBACK
FROM @SMART_RETAIL_INDIA.RAW_LAYER.s3_stg/DIM_CUSTOMER_FEEDBACK/
FILE_FORMAT = (FORMAT_NAME = 'SMART_RETAIL_INDIA.RAW_LAYER.csv_ff')
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_CUSTOMER
    AUTO_INGEST = TRUE
AS
COPY INTO SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER
FROM @SMART_RETAIL_INDIA.RAW_LAYER.s3_stg/DIM_CUSTOMER/
FILE_FORMAT = (FORMAT_NAME = 'SMART_RETAIL_INDIA.RAW_LAYER.json_ff')
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_PRODUCT
    AUTO_INGEST = TRUE
AS
COPY INTO SMART_RETAIL_INDIA.RAW_LAYER.DIM_PRODUCT
FROM @SMART_RETAIL_INDIA.RAW_LAYER.s3_stg/DIM_PRODUCT/
FILE_FORMAT = (FORMAT_NAME = 'SMART_RETAIL_INDIA.RAW_LAYER.json_ff')
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_DATE
    AUTO_INGEST = TRUE
AS
COPY INTO SMART_RETAIL_INDIA.RAW_LAYER.DIM_DATE
FROM @SMART_RETAIL_INDIA.RAW_LAYER.s3_stg/DIM_DATE/
FILE_FORMAT = (FORMAT_NAME = 'SMART_RETAIL_INDIA.RAW_LAYER.json_ff')
ON_ERROR = CONTINUE;


SELECT 'PIPE_FACT_SALES'            AS pipe_name, PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_FACT_SALES'))['notificationChannelName']::VARCHAR            AS sqs_arn
UNION ALL
SELECT 'PIPE_FACT_SALES_TARGET',    PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_FACT_SALES_TARGET'))['notificationChannelName']::VARCHAR
UNION ALL
SELECT 'PIPE_DIM_INVENTORY',        PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_INVENTORY'))['notificationChannelName']::VARCHAR
UNION ALL
SELECT 'PIPE_DIM_CUSTOMER_FEEDBACK',PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_CUSTOMER_FEEDBACK'))['notificationChannelName']::VARCHAR
UNION ALL
SELECT 'PIPE_DIM_CUSTOMER',         PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_CUSTOMER'))['notificationChannelName']::VARCHAR
UNION ALL
SELECT 'PIPE_DIM_PRODUCT',          PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_PRODUCT'))['notificationChannelName']::VARCHAR
UNION ALL
SELECT 'PIPE_DIM_DATE',          PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_DATE'))['notificationChannelName']::VARCHAR;

/*TRUNCATE TABLE SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES;
TRUNCATE TABLE SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES_TARGET;
TRUNCATE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_INVENTORY;
TRUNCATE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER_FEEDBACK;
TRUNCATE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER;
TRUNCATE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_PRODUCT;*/

ALTER PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_FACT_SALES SET PIPE_EXECUTION_PAUSED = FALSE;
ALTER PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_FACT_SALES_TARGET SET PIPE_EXECUTION_PAUSED = FALSE;
ALTER PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_INVENTORY SET PIPE_EXECUTION_PAUSED = FALSE;
ALTER PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_CUSTOMER_FEEDBACK SET PIPE_EXECUTION_PAUSED = FALSE;
ALTER PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_CUSTOMER SET PIPE_EXECUTION_PAUSED = FALSE;
ALTER PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_PRODUCT SET PIPE_EXECUTION_PAUSED = FALSE;
ALTER PIPE SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_DATE SET PIPE_EXECUTION_PAUSED = FALSE;

SELECT PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_FACT_SALES'))['executionState']::VARCHAR            AS PIPE_FACT_SALES,
       PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_FACT_SALES_TARGET'))['executionState']::VARCHAR    AS PIPE_FACT_SALES_TARGET,
       PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_INVENTORY'))['executionState']::VARCHAR        AS PIPE_DIM_INVENTORY,
       PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_CUSTOMER_FEEDBACK'))['executionState']::VARCHAR AS PIPE_DIM_CUSTOMER_FEEDBACK,
       PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_CUSTOMER'))['executionState']::VARCHAR         AS PIPE_DIM_CUSTOMER,
       PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_PRODUCT'))['executionState']::VARCHAR          AS PIPE_DIM_PRODUCT,
       PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_DIM_DATE'))['executionState']::VARCHAR          AS 
PIPE_DIM_DATE;

       SELECT COUNT(*) FROM SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES;

       SELECT 'FACT_SALES'              AS table_name, COUNT(*) AS row_count FROM SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES
UNION ALL
SELECT 'FACT_SALES_TARGET',                     COUNT(*)              FROM SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES_TARGET
UNION ALL
SELECT 'DIM_INVENTORY',                         COUNT(*)              FROM SMART_RETAIL_INDIA.RAW_LAYER.DIM_INVENTORY
UNION ALL
SELECT 'DIM_CUSTOMER_FEEDBACK',                 COUNT(*)              FROM SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER_FEEDBACK
UNION ALL
SELECT 'DIM_CUSTOMER',                          COUNT(*)              FROM SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER
UNION ALL
SELECT 'DIM_PRODUCT',                           COUNT(*)              FROM SMART_RETAIL_INDIA.RAW_LAYER.DIM_PRODUCT
UNION ALL
SELECT 'DIM_DATE',                           COUNT(*)              FROM SMART_RETAIL_INDIA.RAW_LAYER.DIM_DATE;

CREATE OR REPLACE STREAM SMART_RETAIL_INDIA.RAW_LAYER.STREAM_FACT_SALES
    ON TABLE SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_FACT_SALES
    WAREHOUSE = COMPUTE_WH
    SCHEDULE  = '1 MINUTE'
WHEN
    SYSTEM$STREAM_HAS_DATA('SMART_RETAIL_INDIA.RAW_LAYER.STREAM_FACT_SALES')
AS
INSERT INTO SMART_RETAIL_INDIA.ANALYTICS.FACT_SALES
(
    SALES_ID, DATE_ID, PRODUCT_ID, CUSTOMER_ID, SALESPERSON_ID,
    PROMOTION_ID, PAYMENT_ID,QUANTITY, UNIT_PRICE, SALES_AMOUNT, COST, PROFIT
)
SELECT
    TRIM(SALES_ID),
    TRY_CAST(DATE_ID        AS INT),
    TRIM(PRODUCT_ID),
    TRIM(CUSTOMER_ID),
    TRIM(SALESPERSON_ID),
    TRIM(PROMOTION_ID),
    TRIM(PAYMENT_ID),
    TRY_CAST(QUANTITY       AS INT),
    TRY_CAST(UNIT_PRICE     AS NUMBER(10,2)),
    TRY_CAST(SALES_AMOUNT   AS NUMBER(15,2)),
    TRY_CAST(COST           AS NUMBER(15,2)),
    TRY_CAST(PROFIT         AS NUMBER(15,2))
FROM SMART_RETAIL_INDIA.RAW_LAYER.STREAM_FACT_SALES
WHERE METADATA$ACTION = 'INSERT'
  AND TRY_CAST(DATE_ID AS INT)                  IS NOT NULL
  AND TRY_CAST(QUANTITY AS INT)                 IS NOT NULL
  AND TRY_CAST(SALES_AMOUNT AS NUMBER(15,2))    IS NOT NULL
  AND TRIM(SALES_ID) NOT IN (
        SELECT SALES_ID FROM SMART_RETAIL_INDIA.ANALYTICS.FACT_SALES
  );

  ALTER TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_FACT_SALES RESUME;

  SHOW TASKS IN SCHEMA SMART_RETAIL_INDIA.RAW_LAYER;

  SELECT COUNT(*) FROM SMART_RETAIL_INDIA.ANALYTICS.FACT_SALES;
  SELECT COUNT(*) FROM SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES;
  --select * from STREAM_FACT_SALES;

  SELECT *
FROM TABLE(SMART_RETAIL_INDIA.INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'FACT_SALES',
    START_TIME => DATEADD(HOUR, -1, CURRENT_TIMESTAMP)
))
ORDER BY LAST_LOAD_TIME DESC;

SELECT PARSE_JSON(SYSTEM$PIPE_STATUS('SMART_RETAIL_INDIA.RAW_LAYER.PIPE_FACT_SALES'));

LIST @SMART_RETAIL_INDIA.RAW_LAYER.s3_stg/FACT_SALES/;

/*TRUNCATE TABLE SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES_TARGET;
TRUNCATE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_INVENTORY;
TRUNCATE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER_FEEDBACK;
TRUNCATE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER;
TRUNCATE TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_PRODUCT;*/





CREATE OR REPLACE STREAM SMART_RETAIL_INDIA.RAW_LAYER.STREAM_FACT_SALES_TARGET
    ON TABLE SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES_TARGET
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_FACT_SALES_TARGET
    WAREHOUSE = COMPUTE_WH
    SCHEDULE  = '1 MINUTE'
WHEN
    SYSTEM$STREAM_HAS_DATA('SMART_RETAIL_INDIA.RAW_LAYER.STREAM_FACT_SALES_TARGET')
AS
INSERT INTO SMART_RETAIL_INDIA.ANALYTICS.FACT_SALES_TARGET
(
    TARGET_ID, DATE_ID,SALESPERSON_ID, CUSTOMER_SEGMENT_ID, TARGET_AMOUNT
)
SELECT
    TRIM(TARGET_ID),
    TRY_CAST(DATE_ID            AS INT),
    TRIM(SALESPERSON_ID),
    TRIM(CUSTOMER_SEGMENT_ID),
    TRY_CAST(TARGET_AMOUNT      AS NUMBER(15,2))
FROM SMART_RETAIL_INDIA.RAW_LAYER.STREAM_FACT_SALES_TARGET
WHERE METADATA$ACTION = 'INSERT'
  AND TRY_CAST(DATE_ID AS INT)                  IS NOT NULL
  AND TRY_CAST(TARGET_AMOUNT AS NUMBER(15,2))   IS NOT NULL
  AND TRIM(TARGET_ID) NOT IN (
        SELECT TARGET_ID FROM SMART_RETAIL_INDIA.ANALYTICS.FACT_SALES_TARGET
  );

ALTER TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_FACT_SALES_TARGET RESUME;



CREATE OR REPLACE STREAM SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_INVENTORY
    ON TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_INVENTORY
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_DIM_INVENTORY
    WAREHOUSE = COMPUTE_WH
    SCHEDULE  = '1 MINUTE'
WHEN
    SYSTEM$STREAM_HAS_DATA('SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_INVENTORY')
AS
INSERT INTO SMART_RETAIL_INDIA.ANALYTICS.DIM_INVENTORY
(
    INVENTORY_ID, DATE_ID, PRODUCT_ID,
    STOCK_IN, STOCK_OUT, AVAILABLE_STOCK,
    REORDER_LEVEL, SAFETY_STOCK, STOCK_STATUS
)
SELECT
    TRIM(INVENTORY_ID),
    TRY_CAST(DATE_ID            AS INT),
    TRIM(PRODUCT_ID),
    TRY_CAST(STOCK_IN           AS INT),
    TRY_CAST(STOCK_OUT          AS INT),
    TRY_CAST(AVAILABLE_STOCK    AS INT),
    TRY_CAST(REORDER_LEVEL      AS INT),
    TRY_CAST(SAFETY_STOCK       AS INT),
    TRIM(STOCK_STATUS)
FROM SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_INVENTORY
WHERE METADATA$ACTION = 'INSERT'
  AND TRY_CAST(DATE_ID AS INT)       IS NOT NULL
  AND TRY_CAST(STOCK_IN AS INT)      IS NOT NULL
  AND TRIM(INVENTORY_ID) NOT IN (
        SELECT INVENTORY_ID FROM SMART_RETAIL_INDIA.ANALYTICS.DIM_INVENTORY
  );

ALTER TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_DIM_INVENTORY RESUME;


CREATE OR REPLACE STREAM SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_CUSTOMER_FEEDBACK
ON TABLE SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER_FEEDBACK
APPEND_ONLY = TRUE;


-- =============================================
-- DIM_CUSTOMER_FEEDBACK (CSV)
-- =============================================
CREATE OR REPLACE TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_DIM_CUSTOMER_FEEDBACK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_CUSTOMER_FEEDBACK')
AS
INSERT INTO SMART_RETAIL_INDIA.ANALYTICS.DIM_CUSTOMER_FEEDBACK
(FEEDBACK_ID, CUSTOMER_ID, PRODUCT_ID, DATE_ID,
 FEEDBACK_TYPE, RATING, COMMENT, CHANNEL,
 SENTIMENT, RESOLUTION_STATUS, RESPONSE_TIME)
SELECT
    TRIM(S.FEEDBACK_ID),
    TRIM(S.CUSTOMER_ID),
    TRIM(S.PRODUCT_ID),
    TRY_CAST(S.DATE_ID AS INT),
    TRIM(S.FEEDBACK_TYPE),
    TRY_CAST(S.RATING AS NUMBER(2,1)),
    TRIM(S.COMMENT),
    TRIM(S.CHANNEL),
    TRIM(S.SENTIMENT),
    TRIM(S.RESOLUTION_STATUS),
    TRY_CAST(S.RESPONSE_TIME AS NUMBER(5,2))
FROM SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_CUSTOMER_FEEDBACK S
WHERE S.METADATA$ACTION = 'INSERT'
AND TRY_CAST(S.DATE_ID AS INT) IS NOT NULL
AND TRY_CAST(S.RATING AS NUMBER(2,1)) IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM SMART_RETAIL_INDIA.ANALYTICS.DIM_CUSTOMER_FEEDBACK A
    WHERE A.FEEDBACK_ID = TRIM(S.FEEDBACK_ID)
);
ALTER TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_DIM_CUSTOMER_FEEDBACK RESUME;

-- =============================================
-- DIM_CUSTOMER (JSON)
-- =============================================
CREATE OR REPLACE TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_DIM_CUSTOMER
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_CUSTOMER')
AS
INSERT INTO SMART_RETAIL_INDIA.ANALYTICS.DIM_CUSTOMER
(CUSTOMER_ID, SEGMENT_ID, CUSTOMER_NAME, GENDER,
 AGE, CITY, STATE, INCOME_GROUP, REGISTRATION_DATE)
SELECT
    S.RAW_DATA:CUSTOMER_ID::VARCHAR,
    S.RAW_DATA:SEGMENT_ID::VARCHAR,
    S.RAW_DATA:CUSTOMER_NAME::VARCHAR,
    S.RAW_DATA:GENDER::VARCHAR,
    S.RAW_DATA:AGE::INT,
    S.RAW_DATA:CITY::VARCHAR,
    S.RAW_DATA:STATE::VARCHAR,
    S.RAW_DATA:INCOME_GROUP::VARCHAR,
    S.RAW_DATA:REGISTRATION_DATE::DATE
FROM SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_CUSTOMER S
WHERE S.METADATA$ACTION = 'INSERT'
AND S.RAW_DATA:CUSTOMER_ID::VARCHAR IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM SMART_RETAIL_INDIA.ANALYTICS.DIM_CUSTOMER A
    WHERE A.CUSTOMER_ID = S.RAW_DATA:CUSTOMER_ID::VARCHAR
);
ALTER TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_DIM_CUSTOMER RESUME;

-- =============================================
-- DIM_PRODUCT (JSON)
-- =============================================
CREATE OR REPLACE TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_DIM_PRODUCT
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_PRODUCT')
AS
INSERT INTO SMART_RETAIL_INDIA.ANALYTICS.DIM_PRODUCT
(PRODUCT_ID, CATEGORY_ID, PRODUCT_NAME, SKU, BRAND,
 UNIT_COST, UNIT_PRICE, SIZE, COLOR, LAUNCH_DATE, PRODUCT_STATUS)
SELECT
    S.RAW_DATA:PRODUCT_ID::VARCHAR,
    S.RAW_DATA:CATEGORY_ID::VARCHAR,
    S.RAW_DATA:PRODUCT_NAME::VARCHAR,
    S.RAW_DATA:SKU::VARCHAR,
    S.RAW_DATA:BRAND::VARCHAR,
    S.RAW_DATA:UNIT_COST::NUMBER(10,2),
    S.RAW_DATA:UNIT_PRICE::NUMBER(10,2),
    S.RAW_DATA:SIZE::VARCHAR,
    S.RAW_DATA:COLOR::VARCHAR,
    S.RAW_DATA:LAUNCH_DATE::DATE,
    S.RAW_DATA:PRODUCT_STATUS::VARCHAR
FROM SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_PRODUCT S
WHERE S.METADATA$ACTION = 'INSERT'
AND S.RAW_DATA:PRODUCT_ID::VARCHAR IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM SMART_RETAIL_INDIA.ANALYTICS.DIM_PRODUCT A
    WHERE A.PRODUCT_ID = S.RAW_DATA:PRODUCT_ID::VARCHAR
);
ALTER TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_DIM_PRODUCT RESUME;

-- =============================================
-- DIM_DATE (JSON)
-- =============================================
CREATE OR REPLACE TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_DIM_DATE
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_DATE')
AS
INSERT INTO SMART_RETAIL_INDIA.ANALYTICS.DIM_DATE
(DATE_ID, FULL_DATE, DAY_NAME, DAY_OF_MONTH,
 MONTH, QUARTER, YEAR, FISCAL_YEAR,
 IS_WEEKEND, IS_HOLIDAY, HOLIDAY_NAME)
SELECT
    S.RAW_DATA:DATE_ID::INT,
    S.RAW_DATA:FULL_DATE::DATE,
    S.RAW_DATA:DAY_NAME::VARCHAR,
    S.RAW_DATA:DAY_OF_MONTH::INT,
    S.RAW_DATA:MONTH::VARCHAR,
    S.RAW_DATA:QUARTER::VARCHAR,
    S.RAW_DATA:YEAR::INT,
    S.RAW_DATA:FISCAL_YEAR::VARCHAR,
    S.RAW_DATA:IS_WEEKEND::BOOLEAN,
    S.RAW_DATA:IS_HOLIDAY::BOOLEAN,
    S.RAW_DATA:HOLIDAY_NAME::VARCHAR
FROM SMART_RETAIL_INDIA.RAW_LAYER.STREAM_DIM_DATE S
WHERE S.METADATA$ACTION = 'INSERT'
AND S.RAW_DATA:DATE_ID::INT IS NOT NULL
AND NOT EXISTS (
    SELECT 1 FROM SMART_RETAIL_INDIA.ANALYTICS.DIM_DATE A
    WHERE A.DATE_ID = S.RAW_DATA:DATE_ID::INT
);
ALTER TASK SMART_RETAIL_INDIA.RAW_LAYER.TASK_DIM_DATE RESUME;



SHOW TASKS IN SCHEMA SMART_RETAIL_INDIA.RAW_LAYER;

SELECT NAME, STATE, ERROR_CODE, ERROR_MESSAGE, SCHEDULED_TIME
FROM TABLE(SMART_RETAIL_INDIA.INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY SCHEDULED_TIME DESC
LIMIT 20;


SELECT 'FACT_SALES'             AS table_name, COUNT(*) AS row_count FROM SMART_RETAIL_INDIA.ANALYTICS.FACT_SALES
UNION ALL
SELECT 'FACT_SALES_TARGET',                    COUNT(*)              FROM SMART_RETAIL_INDIA.ANALYTICS.FACT_SALES_TARGET
UNION ALL
SELECT 'DIM_INVENTORY',                        COUNT(*)              FROM SMART_RETAIL_INDIA.ANALYTICS.DIM_INVENTORY
UNION ALL
SELECT 'DIM_CUSTOMER_FEEDBACK',                COUNT(*)              FROM SMART_RETAIL_INDIA.ANALYTICS.DIM_CUSTOMER_FEEDBACK
UNION ALL
SELECT 'DIM_CUSTOMER',                         COUNT(*)              FROM SMART_RETAIL_INDIA.ANALYTICS.DIM_CUSTOMER
UNION ALL
SELECT 'DIM_PRODUCT',                          COUNT(*)              FROM SMART_RETAIL_INDIA.ANALYTICS.DIM_PRODUCT
UNION ALL
SELECT 'DIM_DATE',                               COUNT(*)              FROM SMART_RETAIL_INDIA.ANALYTICS.DIM_DATE;

SELECT 'FACT_SALES'             AS table_name, COUNT(*) AS row_count FROM SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES
UNION ALL
SELECT 'FACT_SALES_TARGET',                    COUNT(*)              FROM SMART_RETAIL_INDIA.RAW_LAYER.FACT_SALES_TARGET
UNION ALL
SELECT 'DIM_INVENTORY',                        COUNT(*)              FROM SMART_RETAIL_INDIA.RAW_LAYER.DIM_INVENTORY
UNION ALL
SELECT 'DIM_CUSTOMER_FEEDBACK',                COUNT(*)              FROM SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER_FEEDBACK
UNION ALL
SELECT 'DIM_CUSTOMER',                         COUNT(*)              FROM SMART_RETAIL_INDIA.RAW_LAYER.DIM_CUSTOMER
UNION ALL
SELECT 'DIM_PRODUCT',                          COUNT(*)              FROM SMART_RETAIL_INDIA.RAW_LAYER.DIM_PRODUCT
UNION ALL
SELECT 'DIM_DATE',                               COUNT(*)               FROM SMART_RETAIL_INDIA.RAW_LAYER.DIM_DATE;