CREATE DATABASE IF NOT EXISTS SMART_RETAIL_INDIA;
USE DATABASE SMART_RETAIL_INDIA;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;
USE SCHEMA ANALYTICS;


CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID       INT PRIMARY KEY,
    FULL_DATE     DATE,
    DAY_NAME      STRING,
    DAY_OF_MONTH  INT,
    MONTH         STRING,
    QUARTER       STRING,
    YEAR          INT,
    FISCAL_YEAR   STRING,
    IS_WEEKEND    BOOLEAN,
    IS_HOLIDAY    BOOLEAN,
    HOLIDAY_NAME  STRING
);


CREATE OR REPLACE TABLE DIM_PRODUCT_CATEGORY (
    CATEGORY_ID       STRING PRIMARY KEY,
    CATEGORY_NAME     STRING,
    SUB_CATEGORY      STRING,
    DEPARTMENT_NAME   STRING,
    CATEGORY_MANAGER  STRING
);


CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID      STRING PRIMARY KEY,
    CATEGORY_ID     STRING,
    PRODUCT_NAME    STRING,
    SKU             STRING,
    BRAND           STRING,
    UNIT_COST       NUMBER(10,2),
    UNIT_PRICE      NUMBER(10,2),
    SIZE            STRING,
    COLOR           STRING,
    LAUNCH_DATE     DATE,
    PRODUCT_STATUS  STRING,

    FOREIGN KEY (CATEGORY_ID) REFERENCES DIM_PRODUCT_CATEGORY(CATEGORY_ID)
);


CREATE OR REPLACE TABLE DIM_CUSTOMER_SEGMENT (
    SEGMENT_ID          STRING PRIMARY KEY,
    SEGMENT_NAME        STRING,
    SEGMENT_DESCRIPTION STRING,
    PRIORITY_LEVEL      INT
);

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID        STRING PRIMARY KEY,
    SEGMENT_ID         STRING,
    CUSTOMER_NAME      STRING,
    GENDER             STRING,
    AGE                INT,
    CITY               STRING,
    STATE              STRING,          
    INCOME_GROUP       STRING,
    REGISTRATION_DATE  DATE,

    FOREIGN KEY (SEGMENT_ID) REFERENCES DIM_CUSTOMER_SEGMENT(SEGMENT_ID)
);


CREATE OR REPLACE TABLE DIM_SALESPERSON (
    SALESPERSON_ID      STRING PRIMARY KEY,
    SALESPERSON_NAME    STRING,
    DESIGNATION         STRING,
    YEARS_OF_EXPERIENCE INT,
    HIRE_DATE           DATE,
    STATUS              STRING
);


CREATE OR REPLACE TABLE DIM_PROMOTION (
    PROMOTION_ID          STRING PRIMARY KEY,
    PROMOTION_NAME        STRING,
    PROMOTION_TYPE        STRING,
    DISCOUNT_PERCENTAGE   NUMBER(5,2),
    CHANNEL               STRING,
    START_DATE            DATE,
    END_DATE              DATE,
    STATUS                STRING
);

CREATE OR REPLACE TABLE DIM_PAYMENT (
    PAYMENT_ID      STRING PRIMARY KEY,
    PAYMENT_METHOD  STRING,
    PROVIDER        STRING,
    TRANSACTION_FEE NUMBER(10,2),
    PAYMENT_STATUS  STRING
);


CREATE OR REPLACE TABLE DIM_INVENTORY (
    INVENTORY_ID     STRING PRIMARY KEY,
    DATE_ID          INT,
    PRODUCT_ID       STRING,
    STOCK_IN         INT,
    STOCK_OUT        INT,
    AVAILABLE_STOCK  INT,
    REORDER_LEVEL    INT,
    SAFETY_STOCK     INT,
    STOCK_STATUS     STRING,

    FOREIGN KEY (DATE_ID)    REFERENCES DIM_DATE(DATE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID)
);


CREATE OR REPLACE TABLE DIM_CUSTOMER_FEEDBACK (
    FEEDBACK_ID        STRING PRIMARY KEY,
    CUSTOMER_ID        STRING,
    PRODUCT_ID         STRING,
    DATE_ID            INT,
    FEEDBACK_TYPE      STRING,
    RATING             NUMBER(2,1),
    COMMENT            STRING,
    CHANNEL            STRING,
    SENTIMENT          STRING,
    RESOLUTION_STATUS  STRING,
    RESPONSE_TIME      NUMBER(5,2),

    FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID)  REFERENCES DIM_PRODUCT(PRODUCT_ID),
    FOREIGN KEY (DATE_ID)     REFERENCES DIM_DATE(DATE_ID)
);


CREATE OR REPLACE TABLE FACT_SALES (
    SALES_ID        STRING PRIMARY KEY,
    DATE_ID         INT,
    PRODUCT_ID      STRING,
    CUSTOMER_ID     STRING,
    SALESPERSON_ID  STRING,
    PROMOTION_ID    STRING,
    PAYMENT_ID      STRING,

    QUANTITY        INT,
    UNIT_PRICE NUMBER(10,2),
    SALES_AMOUNT    NUMBER(15,2),
    COST            NUMBER(15,2),
    PROFIT          NUMBER(15,2),

    FOREIGN KEY (DATE_ID)        REFERENCES DIM_DATE(DATE_ID),
    FOREIGN KEY (PRODUCT_ID)     REFERENCES DIM_PRODUCT(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID)    REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (SALESPERSON_ID) REFERENCES DIM_SALESPERSON(SALESPERSON_ID),
    FOREIGN KEY (PROMOTION_ID)   REFERENCES DIM_PROMOTION(PROMOTION_ID),
    FOREIGN KEY (PAYMENT_ID)     REFERENCES DIM_PAYMENT(PAYMENT_ID)
);


CREATE OR REPLACE TABLE FACT_SALES_TARGET (
    TARGET_ID           STRING PRIMARY KEY,
    DATE_ID             INT,
    SALESPERSON_ID      STRING,
    CUSTOMER_SEGMENT_ID STRING,
    TARGET_AMOUNT       NUMBER(15,2),

    FOREIGN KEY (DATE_ID)           REFERENCES DIM_DATE(DATE_ID),
    FOREIGN KEY (SALESPERSON_ID)    REFERENCES DIM_SALESPERSON(SALESPERSON_ID),
    FOREIGN KEY (CUSTOMER_SEGMENT_ID) REFERENCES DIM_CUSTOMER_SEGMENT(SEGMENT_ID)
);
